<Project>
  <ItemGroup>
    <!-- ASP.NET Core -->
    <PackageVersion  Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
    
    <!-- Entity Framework Core -->
    <PackageVersion  Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
    <PackageVersion  Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    <PackageVersion  Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22" />

    <!-- Swagger / OpenAPI -->
    <PackageVersion  Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>
</Project>